services:
  lymdunette-bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - steam-news-data:/app/data

volumes:
  steam-news-data:
